/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.getGreeting(), "Hello World!");
    }
    @Test
    void canAddTaskToList() {
        App app = new App();
        assertTrue(app.addTask("Buy milk"));
        assertEquals(1, app.getTasks().size());
        assertEquals("Buy milk", app.getTasks().get(0));
    }

    @Test
    void cannotAddEmptyTask() {
        App app = new App();
        assertFalse(app.addTask(""));
        assertEquals(0, app.getTasks().size());
    }
  
}